
export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"

export const CARTITEM_LIST_SUCCESS="CARTITEM_LIST_SUCCESS"

export const INCREAMENT_COUNTER="INCREAMENT_COUNTER"
export const DECREAMENT_COUNTER="DECREAMENT_COUNTER"